flowchart LR
    UA[User A] -->|http request| S1[Server 1<br/>session A<br/>profile A]
    UB[User B] -->|http request| S2[Server 2<br/>session B<br/>profile B]
    UC[User C] -->|http request| S3[Server 3<br/>session C<br/>profile C]
